name: Build and Push Container Image
description: Builds a container image using Buildah and pushes it to GitHub Container Registry (GHCR).

inputs:
  image:
    description: Name of the image to build
    required: true
  owner:
    description: Owner of the repository where the image will be pushed
    required: true
  actor:
    description: GitHub actor (username) for authentication
    required: true
  token:
    description: GitHub token with permissions to push to the registry
    required: true
  push:
    description: Whether to push the image to the registry (true/false)
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build container image
      id: image-build
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ inputs.image }}
        tags: latest
        containerfiles: |
          ./Containerfile

    - name: Log in to registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: ghcr.io/${{ inputs.owner }}
        username: ${{ inputs.actor }}
        password: ${{ inputs.token }}

    - name: Push image to registry
      if: ${{ inputs.push == 'true' }}
      uses: redhat-actions/push-to-registry@v2
      with:
        registry: ghcr.io/${{ inputs.owner}}
        image: ${{ steps.image-build.outputs.image }}
        tags: ${{ steps.image-build.outputs.tags }}

    - name: Remove untagged images
      uses: actions/delete-package-versions@v5
      with:
        owner: ${{ inputs.owner }}
        token: ${{ inputs.token }}
        package-type: container
        package-name: ${{ inputs.image }}
        delete-only-untagged-versions: true
