name: Build and Push Container Image
description: "Builds a container image using Buildah and pushes it to a specified container registry."

inputs:
  image_name:
    description: "Name of the image to build"
    required: true
  registry_name:
    description: "Container registry to push to"
    required: true
  registry_username:
    description: "Username for the container registry"
    required: true
  registry_password:
    description: "Password for the container registry"
    required: true
  push:
    description: "Whether to push the image to the registry (true/false)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build container image
      id: image-build
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ inputs.image_name }}
        tags: latest
        containerfiles: |
          ./Containerfile

    - name: Log in to registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: ${{ inputs.registry_name }}
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}

    - name: Push image to registry
      if: ${{ inputs.push == 'true' }}
      uses: redhat-actions/push-to-registry@v2
      with:
        registry: ${{ inputs.registry }}
        image: ${{ steps.image-build.outputs.image }}
        tags: ${{ steps.image-build.outputs.tags }}

    - name: Remove untagged images
      uses: actions/delete-package-versions@v5
      with:
        package-type: container
        package-name: ${{ inputs.image_name }}
        delete-only-untagged-versions: true
