name: Build container image and push to GHCR only on the default branch

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IS_DEFAULT_BRANCH: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}

    steps:
      - uses: actions/checkout@v4

      - name: Build image
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ github.event.repository.name }}
          tags: latest
          containerfiles: ./Containerfile

      - name: Log in to GHCR
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        if: env.IS_DEFAULT_BRANCH == 'true'
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ghcr.io
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}

      - name: Clean up images
        if: env.IS_DEFAULT_BRANCH == 'true'
        uses: actions/delete-package-versions@v5
        with:
          owner: ${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}
          package-type: container
          package-name: ${{ github.event.repository.name }}
          delete-only-untagged-versions: true
          min-versions-to-keep: 1
