name: Build and push container image to GHCR

on:
  workflow_call:

env:
  IMAGE: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}

jobs:
  metadata:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}

    steps:
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.IMAGE }}
          tags: |
            # "latest" only on default branch
            type=raw,value=latest,enable={{is_default_branch}}
            # otherwise branch name
            type=ref,event=branch

  build:
    needs: metadata

    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-24.04
            platform: linux/amd64
          - arch: arm64
            runner: ubuntu-24.04-arm
            platform: linux/arm64
    
    runs-on: ${{ matrix.runner }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (by digest)
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ matrix.platform }}
          labels: ${{ needs.metadata.outputs.labels }}
          outputs: type=registry,push-by-digest=true,name=${{ env.IMAGE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          sbom: false

      - name: Export image digest ref
        run: |
          echo "${{ env.IMAGE }}@${{ steps.build.outputs.digest }}" > "digest-${{ matrix.arch }}.txt"

      - name: Upload digests artifact
        uses: actions/upload-artifact@v4
        with:
          name: digest-${{ matrix.arch }}
          path: digest-${{ matrix.arch }}.txt

  merge:
    needs: [metadata, build]

    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write

    steps:
      - name: Download digests
        uses: actions/download-artifact@v5
        with:
          pattern: digest-*
          merge-multiple: true
          path: digests

      - name: Set up Docker Buildx (for imagetools)
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push multi-arch manifest
        env:
          TAGS: ${{ needs.metadata.outputs.tags }}
        run: |
          TAG_ARGS=""
          # metadata-action outputs tags as newline-separated values
          while IFS= read -r tag; do
            [ -z "$tag" ] && continue
            TAG_ARGS="$TAG_ARGS -t $tag"
          done <<< "$TAGS"

          REFS=$(paste -sd " " digests/*.txt)
          docker buildx imagetools create $TAG_ARGS $REFS
